version: "2.2"
services:
  tests:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "5050:5050"
    networks:
      - test_network

networks:
  test_network:
    driver: bridge
